name: Run Cypress Tests with Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Start dev server
        run: npm run dev &
      
      - name: Wait for dev server to be ready
        run: npx wait-on http://localhost:3000

      - name: Run Cypress tests
        run: npx cypress run

      - name: Generate Cypress report with mochawesome
        run: npm run generate-report

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: cypress/reports/*.html
